Cart/urls.py
from django.urls import path
from . import views

app_name ='Cart'
urlpatterns = [
    path('',views.view_cart,name='view_cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('update_qty/',views.update_qty, name='update_qty'),
    path('remove_item/<int:id>/',views.remove_item, name='remove_item'),
    path('check_out/',views.check_out, name='check_out'),
    # path('apply_coupon/',views.apply_coupon, name='apply_coupon'),
]                   

Ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admins/', admin.site.urls),
    path('',include('Home.urls')),
    path('login/',include('Accounts.urls')),
    path('product/',include('Product.urls')),
    path('users/',include('Users.urls')),
    path('accounts/', include('allauth.urls')),
    path('brands/',include('Brands.urls')),
    path('cart/', include('Cart.urls')),
    path('order/', include('Order.urls')),
    path('offers/', include('Offers.urls')),
    path('wishlist/', include('Wishlist.urls')),
    path('coupon/', include('Coupons.urls')),
    path('wallet/', include('Wallet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'
urlpatterns = [
    path('',views.user_home,name='user_home'),
    path('admin-home/',views.admin_home,name='admin_home')    
]

Order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ='Order'
urlpatterns = [
    path('',views.place_order,name='place_order'),
    path('order_list/',views.order_list,name='order_list'),
    path('all_order/',views.user_order,name='user_order'),
    path('order_items/<int:id>',views.order_items,name='order_items'),
    path('user_order_details/<int:id>',views.user_order_details,name='user_order_details'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel_order'),
    path('order_status/<int:id>',views.order_status,name='order_status'),
    path('request_return/<int:id>',views.request_return,name='request_return'),
    path('payment_success/',views.payment_success,name='payment_success'),
    path('verify_payment/',views.verify_payment,name='verify_payment'),
    path('success/',views.success,name='success'),
    path('retry_payment/<int:order_id>/', views.retry_payment, name='retry_payment'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    path('remove_coupon/',views.remove_coupon,name='remove_coupon'),
    path('download-invoice/<int:order_item_id>/', views.generate_invoice, name='download_invoice')
  
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)                

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from . import views

app_name = 'Users'

urlpatterns = [
    path('',views.users,name='users'),
    path('block/<int:id>/', views.block, name='block'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('new_address/', views.new_address, name='new_address'),
    path('edit_address/<int:id>/', views.edit_address, name='edit_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('all_address/', views.all_address, name='all_address'),
    path('edit_details/', views.edit_details, name='edit_details'),
     path('add-new-address/', views.add_new_address, name='add_new_address'),
]

Wallet/urls.py
from django.urls import path
from . import views
app_name ='Wallet'
urlpatterns = [
    path('',views.transactions,name='transactions')

  
    
]

templates/profile_base/profile_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Essence - Fashion Ecommerce Template</title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <style>
        .profile-container {
            display: flex;
            flex-wrap: wrap;
            margin: 20px;
            height: 100%;
            width: 22vw
        }

        .profile-sidebar {
            flex: 1;
            width:22vw
            max-width: 250px;
            background-color: #f7f7f7;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .profile-sidebar img {
            width: 50px;
            border-radius: 50%;
            margin-right: 10px;
        }

        .profile-sidebar h2 {
            font-size: 18px;
            margin: 0;
        }

        .profile-menu {
            margin-top: 30px;
        }

        .profile-menu a {
            display: block;
            padding: 10px 0;
            font-size: 16px;
            color: #333;
            text-decoration: none;
            border-bottom: 1px solid #ddd;
        }

        .profile-content {
            flex: 3;
            background-color: transparent;
            
            margin-left: 20px;
        }

        .profile-content h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        .user-form {
            display: flex;
            flex-direction: column;
            width: 50%;
        }

        .input-group {
            margin-bottom: 15px;
            width: 50%;
        }

        .input-group label {
            margin-bottom: 5px;
            font-weight: bold;
        }

        .input-group input[type="text"],
        .input-group input[type="email"],
        .input-group input[type="tel"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .gender-options {
            display: flex;
            align-items: center;
        }

        .gender-options label {
            margin-right: 15px;
        }

        .edit-btn {
            background-color: #0066ff;
            color: white;
            padding: 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: 15vw;
            
        }

        .edit-btn:hover {
            background-color: #0052cc;
        }

        @media (max-width: 768px) {
            .profile-container {
                flex-direction: column;
            }

            .profile-sidebar,
            .profile-content {
                margin-left: 0;
                max-width: 100%;
                    
            }
        }

        
    </style>

</head>

<body>
    <!-- Header -->
    <header class="header_area">
        <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
            <!-- Classy Menu -->
            <nav class="classy-navbar" id="essenceNav">
                <!-- Logo -->
                <a class="nav-brand" href="{% url 'Home:user_home' %}">SyncWise</a>
                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span>
                        
                    </span><span></span><span></span></span>
                    
                </div>
                <!-- Menu -->
                <div class="classy-menu">
                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>

                    <div class=" d-lg-none d-md-flex container-fluid row">
                        <div class="profile-container col-12">
                            <!-- Sidebar -->
                            <div class="profile-sidebar">
                                <div class="profile-info">
                                    <img src="{% static 'img/core-img/user.svg' %}" alt="User Avatar">
                                    <h2>Hello<br>{{user_obj.first_name}} {{user_obj.last_name}}</h2>
                                </div>
                                <div class="profile-menu">
                                    <a href="{% url 'Users:user_profile'%}">My Account</a>
                                    <a href="{% url 'Order:user_order' %}">My Orders</a>
                                    <a href="{% url 'Wishlist:wishlist' %}">Favourites</a>
                                    <a href="{% url 'Users:all_address'%}">Saved Address</a>
     
                                    <a href="{% url 'Wallet:transactions'%}">Wallet</a>
                                    <a href="{% url 'Accounts:logout_user' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </nav>





            <!-- Header Meta Data -->
            <div class="header-meta d-flex clearfix justify-content-end">
                <!-- Search Area -->
                <div class="search-area">
                    <form action="#" method="post">
                        <input type="search" name="search" id="headerSearch" placeholder="Type for search">
                        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
                <!-- Favourite Area -->
                <div class="favourite-area">
                    <a href="#"><img src="{% static 'img/core-img/heart.svg' %}" alt=""></a>
                </div>
                <!-- User Login Info -->
                <div class="user-login-info">
                    <a href="{% url 'Users:user_profile' %}"><img src="{% static 'img/core-img/user.svg' %}" alt=""></a>
                </div>
                <!-- Cart Area -->
                <div class="cart-area">
                    <a href="#" id="essenceCartBtn"><img src="{% static 'img/core-img/bag.svg' %}" alt=""> <span></span></a>
                </div>
            </div>

        </div>
    </header>

    <!-- Breadcrumb Area -->
    <div class="breadcumb_area bg-img" style="background-image: url({% static 'img/bg-img/breadcumb.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                         {% block header %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Profile Section -->
    
    <div class="d-flex">
        <div class="d-none d-md-flex ">
            <div class="profile-container">
                <!-- Sidebar -->
                <div class="profile-sidebar">
                    <div class="profile-info">
                        <img src="{% static 'img/core-img/user.svg' %}" alt="User Avatar">
                        <h2>Hello<br>{{user_obj.first_name}} {{user_obj.last_name}}</h2>
                    </div>
                    <div class="profile-menu">
                        <a href="{% url 'Users:user_profile'%}">My Account</a>
                        <a href="{% url 'Order:user_order' %}">My Orders</a>
                        <a href="{% url 'Wishlist:wishlist' %}">Favourites</a>

                        <a href="{% url 'Users:all_address'%}">Saved Address</a>

                        <a href="{% url 'Wallet:transactions'%}">Wallet</a>
                        <a href="{% url 'Accounts:logout_user' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
       

       
        {% block profile_base %}{% endblock %}

    </div>
























        <!-- Main Content with Profile Form -->
        

    <!-- Footer -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row">
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area d-flex mb-30">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="#"><img src="img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <ul>
                                <li><a href="shop.html">Shop</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area mb-30">
                        <ul class="footer_widget_menu">
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Payment Options</a></li>
                            <li><a href="#">Shipping and Delivery</a></li>
                            <li><a href="#">Guides</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms of Use</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row align-items-end">
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area">
                        <div class="footer_heading mb-30">
                            <h6>Subscribe</h6>
                        </div>
                        <div class="subscribtion_form">
                            <form action="#" method="post">
                                <input type="email" name="mail" class="mail" placeholder="Your email here">
                                <button type="submit" class="submit"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area">
                        <div class="footer_social_area">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Youtube"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>

<div class="row mt-5">
                <div class="col-md-12 text-center">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>, distributed by <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>

        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js'%}"></script>
    <!-- Classy Nav js -->
    <script src="{% static 'js/classy-nav.min.js'%}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>