Brands/urls.py
from django.urls import path
from . import views

app_name ='Brands'
urlpatterns = [
    path('',views.brands_list,name='brands_list'),
    path('create_brand/',views.create_brand,name='create_brand'),
    path('block_brand/<int:id>/', views.block_brand, name='block_brand'),
    path('edit_brand/<int:id>/', views.edit_brand, name='edit_brand'),
]

Cart/urls.py
from django.urls import path
from . import views

app_name ='Cart'
urlpatterns = [
    path('',views.view_cart,name='view_cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('update_qty/',views.update_qty, name='update_qty'),
    path('remove_item/<int:id>/',views.remove_item, name='remove_item'),
    path('check_out/',views.check_out, name='check_out'),
    # path('apply_coupon/',views.apply_coupon, name='apply_coupon'),
]                   

Ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admins/', admin.site.urls),
    path('',include('Home.urls')),
    path('login/',include('Accounts.urls')),
    path('product/',include('Product.urls')),
    path('users/',include('Users.urls')),
    path('accounts/', include('allauth.urls')),
    path('brands/',include('Brands.urls')),
    path('cart/', include('Cart.urls')),
    path('order/', include('Order.urls')),
    path('offers/', include('Offers.urls')),
    path('wishlist/', include('Wishlist.urls')),
    path('coupon/', include('Coupons.urls')),
    path('wallet/', include('Wallet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Offers/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ='Offers'
urlpatterns = [
    
    path('',views.option,name='option'),
    path('product_offer',views.product_offer,name='product_offer'),
    path('add_offer/<int:id>',views.add_offer,name='add_offer'),
    path('edit_offer/<int:id>',views.edit_offer,name='edit_offer'),
    path('delete_offer/<int:id>',views.delete_offer,name='delete_offer'),
    path('brand_offer/<int:id>',views.brand_offer,name='brand_offer'),
    path('edit_brand_offer/<int:id>',views.edit_brand_offer,name='edit_brand_offer'),
    path('brand_offer_list/',views.brand_offer_list,name='brand_offer_list'),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Brands/models.py
from django.db import models

class Brand(models.Model):
    brand_name=models.CharField()
    status=models.BooleanField(default=True)
 

Brands/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Brand
from django.contrib.auth.decorators import login_required,user_passes_test
from django.views.decorators.cache import never_cache
from django.contrib import messages
import re
from Product.views import is_staff
from Offers.models import Brand_Offers


@login_required(login_url='Accounts:admin_login')
@never_cache
@user_passes_test(is_staff,'Accounts:admin_login')
def brands_list(request):
    brands = Brand.objects.all()
    
    # Add offer information directly to the brand objects
    for brand in brands:
        brand_offer = Brand_Offers.objects.filter(brand_id=brand.id, status=True).first()
        brand.offer = brand_offer  # Attach the offer to the brand object

    context = {'brands': brands}
    return render(request, 'brand/brands_list.html', context)


@login_required(login_url='Accounts:admin_login')
@never_cache
@user_passes_test(is_staff,'Accounts:admin_login')
def create_brand(request):
    if request.method == "POST":
        brand_name = request.POST.get('brand_name')

        # Check if brand name is provided
        if not brand_name:
            messages.error(request, 'Brand name is required.')
            return render(request, 'brand/create_brands.html')

        # Check if the brand name contains only white spaces
        if not brand_name.strip():
            messages.error(request, 'Brand name cannot contain only white spaces.')
            return render(request, 'brand/create_brands.html')

        # Check if the brand name is too short
        if len(brand_name.strip()) < 1:
            messages.error(request, 'Brand name must be at least 1 characters long.')
            return render(request, 'brand/create_brands.html')

        # Check if the brand name already exists
        if Brand.objects.filter(brand_name__iexact=(brand_name).strip()).exists():
            messages.error(request, 'Brand already exists.')
            return render(request, 'brand/create_brands.html')

        # If all checks pass, save the new brand
        brand_instance = Brand(brand_name=brand_name.strip())
        brand_instance.save()
        messages.success(request, 'Brand created successfully!')
        return redirect('Product:brand_list')  # Redirect to a relevant page after successful creation

    return render(request, 'brand/create_brands.html')

@login_required(login_url='Accounts:admin_login')
@never_cache
@user_passes_test(is_staff,'Accounts:admin_login')
def edit_brand(request,id):
    brand_id=get_object_or_404(Brand,id=id)
    context={'brand_id':brand_id}
    if request.method=="POST":
        brand_name=request.POST.get('brand_name')
        if not brand_name:
            messages.error(request, 'Brand name is required.')
            return render(request, 'brand/edit_brands.html',context)


        # Check if the brand name contains only white spaces
        if not brand_name.strip():
            messages.error(request, 'Brand name cannot contain only white spaces.')
            return render(request, 'brand/edit_brands.html',context)


        # Check if the brand name is too short
        if len(brand_name.strip()) < 2:
            messages.error(request, 'Brand name must be at least 1 characters long.')
            return render(request, 'brand/edit_brands.html',context)

        # Check if the brand name already exists
        if Brand.objects.filter(brand_name__iexact=brand_name.strip()).exists():
            messages.error(request, 'Brand already exists.')
            return render(request, 'brand/edit_brands.html',context)
        
        if re.search(r'[@!#$%^&*()_+={}\[\]:;"\'<>,.?\\|`~\-]{2,}', brand_name):
            messages.error(request, 'Brand name cannot contain continuous special characters.')
            return render(request, 'brand/edit_brands.html', context)
         
        if re.search(r'\d{2,}', brand_name):
            messages.error(request, 'Brand name cannot contain continuous numbers.')
            return render(request, 'brand/edit_brands.html', context)
        
        brand_id.brand_name=brand_name
        brand_id.save()
        return redirect('Brands:brands_list')
    return render(request,'brand/edit_brands.html',context)
 

@login_required(login_url='Accounts:admin_login')
@never_cache
@user_passes_test(is_staff,'Accounts:admin_login')
def block_brand(request, id):
    brand = get_object_or_404(Brand, id=id)
    brand.status = not brand.status
    brand.save()
    return redirect('Brands:brands_list')

templates/brand/brands_list.html
{% extends "base/base.html" %}

{% block base %}
<div class="main-panel col-10 mx-auto mt-5 mb-5">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-10">
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover align-middle text-center">
                                <thead class="table-dark">
                                    <tr>
                                        <th scope="col">Brand ID</th>
                                        <th scope="col">Brand Name</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Action</th>
                                        <th scope="col">Edit</th>
                                        <th scope="col">Offers</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for brand in brands %}
                                    <tr>
                                        <td>{{ brand.id }}</td>
                                        <td>{{ brand.brand_name }}</td>
                                        <td>
                                            {% if brand.status %}
                                            <span class="text-success">&#xe013;</span>
                                            {% else %}
                                            <span class="text-danger">&#xe014;</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if brand.status %}
                                            <a href="{% url 'Brands:block_brand' brand.id %}" class="badge bg-danger">Block</a>
                                            {% else %}
                                            <a href="{% url 'Brands:block_brand' brand.id %}" class="badge bg-success">Unblock</a>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'Brands:edit_brand' brand.id %}" class="badge bg-warning text-dark">Edit</a>
                                        </td>
                                        <td>
                                            {% if brand.offer %}
                                            <p class="text-success">
                                                {{ brand.offer.offer_price }}% OFF
                                            </p>
                                            {% else %}
                                            <a href="{% url 'Offers:brand_offer' brand.id %}" class="badge bg-warning text-dark">Add Offer</a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="mt-3">
                            <a class="btn btn-outline-info" href="{% url 'Brands:create_brand' %}">Add New Brand</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/brand/create_brands.html
{% extends "base/base.html" %}

{% block base %}
<style>
    /* Basic styling for the form container */
    #variantForm {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Styling for form elements */
    #variantForm label {
        display: block;
        margin-bottom: 8px;
        font-weight: bold;
    }

    #variantForm select,
    #variantForm input {
        width: 100%;
        padding: 10px;
        margin-bottom: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    #variantForm input[type="file"] {
        padding: 0;
    }

    /* Styling for the submit button */
    #submit-button {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #007bff;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
    }

    #submit-button:hover {
        background-color: #0056b3;
    }
</style>


<div class="col-md-8 mx-auto">
    

        {% include 'alerts/alert.html' %}
        <div class="card-body">
            <form id="variantForm" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            
                <!-- Product Name Field -->
                <label for="name">Brand Name:</label>
                <input type="text" name="brand_name" id="name" placeholder="Brand Name" required>
            
                <button type="submit" id="submit-button">Add Brand</button>
            </form>
            </div>
        </div>
   
</div>
            {% endblock %}

templates/brand/edit_brands.html
{% extends "base/base.html" %}

{% block base %}
<style>
    /* Basic styling for the form container */
    #variantForm {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Styling for form elements */
    #variantForm label {
        display: block;
        margin-bottom: 8px;
        font-weight: bold;
    }

    #variantForm select,
    #variantForm input {
        width: 100%;
        padding: 10px;
        margin-bottom: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    #variantForm input[type="file"] {
        padding: 0;
    }

    /* Styling for the submit button */
    #submit-button {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #007bff;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
    }

    #submit-button:hover {
        background-color: #0056b3;
    }
</style>


<div class="col-md-8 mx-auto">
    
        {% include 'alerts/alert.html' %}
        <div class="card-body">
            <form id="variantForm" method="POST" action="{% url 'Brands:edit_brand' brand_id.id %}" enctype="multipart/form-data">
                {% csrf_token %}
            
                <!-- Product Name Field -->
                <label for="name">Brand Name:</label>
                <input type="text" name="brand_name" id="name" placeholder="Brand Name" value="{{brand_id.brand_name}}" required>
            
                <button type="submit" id="submit-button">Change Name</button>
            </form>
            </div>
        </div>
   
</div>
            {% endblock %}