Accounts/urls.py
from django.urls import path
from . import views
from django.shortcuts import render

app_name= 'Accounts'

urlpatterns = [
    path('',views.user_login,name='user_login'),
    path('signup/',views.user_signup,name='user_signup'),
    path('admin_login/',views.admin_login,name='admin_login'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('logout_admin/',views.logout_admin,name='logout_admin'),
    path('verify_otp/',views.verify_otp, name='verify_otp'),
    path('resend_otp/',views.resend_otp, name='resend_otp'),
    path('change_password/',views.change_password, name='change_password'),
    path('set_password/',views.set_password, name='set_password'),
    
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset_done/', lambda request: render(request, 'forgot_password/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', lambda request: render(request, 'forgot_password/password_reset_complete.html'), name='password_reset_complete'),
]

Cart/urls.py
from django.urls import path
from . import views

app_name ='Cart'
urlpatterns = [
    path('',views.view_cart,name='view_cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('update_qty/',views.update_qty, name='update_qty'),
    path('remove_item/<int:id>/',views.remove_item, name='remove_item'),
    path('check_out/',views.check_out, name='check_out'),
    # path('apply_coupon/',views.apply_coupon, name='apply_coupon'),
]                   

Ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admins/', admin.site.urls),
    path('',include('Home.urls')),
    path('login/',include('Accounts.urls')),
    path('product/',include('Product.urls')),
    path('users/',include('Users.urls')),
    path('accounts/', include('allauth.urls')),
    path('brands/',include('Brands.urls')),
    path('cart/', include('Cart.urls')),
    path('order/', include('Order.urls')),
    path('offers/', include('Offers.urls')),
    path('wishlist/', include('Wishlist.urls')),
    path('coupon/', include('Coupons.urls')),
    path('wallet/', include('Wallet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ='Order'
urlpatterns = [
    path('',views.place_order,name='place_order'),
    path('order_list/',views.order_list,name='order_list'),
    path('all_order/',views.user_order,name='user_order'),
    path('order_items/<int:id>',views.order_items,name='order_items'),
    path('user_order_details/<int:id>',views.user_order_details,name='user_order_details'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel_order'),
    path('order_status/<int:id>',views.order_status,name='order_status'),
    path('request_return/<int:id>',views.request_return,name='request_return'),
    path('payment_success/',views.payment_success,name='payment_success'),
    path('verify_payment/',views.verify_payment,name='verify_payment'),
    path('success/',views.success,name='success'),
    path('retry_payment/<int:order_id>/', views.retry_payment, name='retry_payment'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    path('remove_coupon/',views.remove_coupon,name='remove_coupon'),
    path('download-invoice/<int:order_item_id>/', views.generate_invoice, name='download_invoice')
  
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)                

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from . import views

app_name = 'Users'

urlpatterns = [
    path('',views.users,name='users'),
    path('block/<int:id>/', views.block, name='block'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('new_address/', views.new_address, name='new_address'),
    path('edit_address/<int:id>/', views.edit_address, name='edit_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('all_address/', views.all_address, name='all_address'),
    path('edit_details/', views.edit_details, name='edit_details'),
     path('add-new-address/', views.add_new_address, name='add_new_address'),
]

templates/user_profile/address.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Address</h2>{% endblock %}
{% block profile_base %}

<style>
    #state {
        height: 150px; /* Set a fixed height */
        overflow-y: scroll; /* Make it scrollable */
    }
</style>
<div class="col-12 col-md-6">
    {% include 'alerts/alert.html' %}
    <div class="checkout_details_area mt-50 clearfix">

        <div class="cart-page-heading mb-30">
            <h5>Address</h5>
        </div>

        <form  method="POST" action="{% url 'Users:new_address'%}">
             {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-3">
                    <label for="first_name">Name <span>*</span></label>
                    <input type="text" class="form-control" name="name" value="" required>
                </div>
                
                
                <div class="col-12 mb-3">
                    <label for="state">State <span>*</span></label>
                    <select class="w-100 " name="state" style="height: 150px; overflow-y: scroll;">
                        <option value="andhra_pradesh">Select state</option>
                        <option value="andhra_pradesh">Andhra Pradesh</option>
                        <option value="arunachal_pradesh">Arunachal Pradesh</option>
                        <option value="assam">Assam</option>
                        <option value="bihar">Bihar</option>
                        <option value="chhattisgarh">Chhattisgarh</option>
                        <option value="goa">Goa</option>
                        <option value="gujarat">Gujarat</option>
                        <option value="haryana">Haryana</option>
                        <option value="himachal_pradesh">Himachal Pradesh</option>
                        <option value="jharkhand">Jharkhand</option>
                        <option value="karnataka">Karnataka</option>
                        <option value="kerala">Kerala</option>
                        <option value="madhya_pradesh">Madhya Pradesh</option>
                        <option value="maharashtra">Maharashtra</option>
                        <option value="manipur">Manipur</option>
                        <option value="meghalaya">Meghalaya</option>
                        <option value="mizoram">Mizoram</option>
                        <option value="nagaland">Nagaland</option>
                        <option value="odisha">Odisha</option>
                        <option value="punjab">Punjab</option>
                        <option value="rajasthan">Rajasthan</option>
                        <option value="sikkim">Sikkim</option>
                        <option value="tamil_nadu">Tamil Nadu</option>
                        <option value="telangana">Telangana</option>
                        <option value="tripura">Tripura</option>
                        <option value="uttar_pradesh">Uttar Pradesh</option>
                        <option value="uttarakhand">Uttarakhand</option>
                        <option value="west_bengal">West Bengal</option>
                    </select>
                </div>






                
                <div class="col-12 mt-3 mb-3">
                    <label for="postcode" >Pincode <span>*</span></label>
                    <input type="text" name="pincode" class="form-control" id="postcode" value="">
                </div>
                



                
                <div class="col-12 mb-3">
                    <label for="city">Town/City <span>*</span></label>
                    <input type="text" class="form-control" name="city" id="city" value="">
                </div>
                
                
                <div class="col-12 mb-4">
                    <label for="email_address">Email Address <span>*</span></label>
                    <input type="email" name="email" class="form-control" id="email_address" value="">
                </div>
                
                <div class="col-12 mb-3">
                    <label for="phone_number">Phone No <span>*</span></label>
                    <input type="number" class="form-control" name="phone" id="phone_number" min="0" value="">
                </div>
                
                <div class="col-12 mb-3">
                    <label for="street_address">Address <span>*</span></label>
                    <input type="text" class="form-control h-100 mb-3" name="address" id="street_address" value="">
                    
                </div>
                
                
                <div class="col-12 mt-3 ">
                    <label for="city">Landmark<span> (optional)</span></label>
                    <input type="text" class="form-control" name="landmark" id="city" value="">
                </div>
                
            </div>
            <input type="submit" class="btn essence-btn mt-3 mb-3"> 
        </form>
    </div>
</div>
{% endblock %}

templates/user_profile/all_address.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Your Address</h2>{% endblock %}
{% block profile_base %}
    
    <div class="container my-5">
        <h2>Your Addresses</h2>
        <div class="row g-4">
            <!-- Add Address Card -->
            <div class="col-md-4">
                <div class="card h-100 border-dashed">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <a href="{% url 'Users:new_address'%}" class="text-center text-decoration-none">
                            <div class="text-muted">
                                <i class="bi bi-plus-lg" style="font-size: 2rem;"></i>
                                <p class="mt-2">Add address</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Address Card Example 1 -->
            {% for address in addresses%}
            <div class="col-md-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{{address.name}}</h5>
                        <p class="card-text">
                            {{address.city}}<br>
                            {{address.address}}<br>
                            {{address.city}}, {{address.state}} {{address.pincode}}<br>
                            Landmark: {{address.landmark}}<br>
                            {% comment %} India<br> {% endcomment %}
                            Phone number: {{address.phone_no}}<br>
                            Email : {{address.email}}
                        </p>
                       
                        <div class="mt-3">
                            <a href="{% url 'Users:edit_address' address.id %}" class="card-link">Edit</a>
                            <a href="{% url 'Users:delete_address' address.id %}" class="card-link">Remove</a>
                            <a href="#" class="card-link">Set as Default</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- Address Card Example 2 -->
          

            <!-- Address Card Example 3 -->
          
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
{% endblock %}

templates/user_profile/change_password.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Change Password</h2>{% endblock %}
{% block profile_base %}
<form method="POST" action="{% url 'Accounts:change_password' %}">

    <div class="container">
        {% include 'alerts/alert.html' %}
        <div class="row">
            {% csrf_token %}
            <div class="row">

                <div class="col-12 mb-3">
                    <label for="city">Old Password</label>
                    <input type="text" class="form-control" name="old_password" id="old_password" value="">
                </div>


                <div class="col-12 mb-4">
                    <label for="email_address">New Password</label>
                    <input type="text" name="new_password" class="form-control" id="new_password" value="">
                </div>

                <div class="col-12 mb-4">
                    <label for="email_address">Confirm Password</label>
                    <input type="text" name="confirm_password" class="form-control" id="confirm_password" value="">
                </div>


            </div>
        </div>
    </div>

    <input type="submit" value="Confirm" class="btn essence-btn mt-3 mb-3">


</form>
{% endblock %}

templates/user_profile/edit_address.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Edit Address</h2>{% endblock %}
{% block profile_base %}

<style>
    #state {
        height: 150px; /* Set a fixed height */
        overflow-y: scroll; /* Make it scrollable */
    }
</style>
<div class="col-12 col-md-6">
    <div class="checkout_details_area mt-50 clearfix">

        <div class="cart-page-heading mb-30">
            <h5>Address</h5>
        </div>

        <form  method="POST" action="{% url 'Users:edit_address' address.id %}">
             {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-3">
                    <label for="first_name">Name <span>*</span></label>
                    <input type="text" class="form-control" name="name" value="{{address.name}}" required>
                </div>
                
                
                <div class="col-12 mb-3">
                    <label for="state">State <span>*</span></label>
                    <select class="w-100" name="state" style="height: 150px; overflow-y: scroll;">
                        <option value="">Select state</option>
                        <option value="andhra_pradesh" {% if address.state == 'andhra_pradesh' %}selected{% endif %}>Andhra Pradesh</option>
                        <option value="arunachal_pradesh" {% if address.state == 'arunachal_pradesh' %}selected{% endif %}>Arunachal Pradesh</option>
                        <option value="assam" {% if address.state == 'assam' %}selected{% endif %}>Assam</option>
                        <option value="bihar" {% if address.state == 'bihar' %}selected{% endif %}>Bihar</option>
                        <option value="chhattisgarh" {% if address.state == 'chhattisgarh' %}selected{% endif %}>Chhattisgarh</option>
                        <option value="goa" {% if address.state == 'goa' %}selected{% endif %}>Goa</option>
                        <option value="gujarat" {% if address.state == 'gujarat' %}selected{% endif %}>Gujarat</option>
                        <option value="haryana" {% if address.state == 'haryana' %}selected{% endif %}>Haryana</option>
                        <option value="himachal_pradesh" {% if address.state == 'himachal_pradesh' %}selected{% endif %}>Himachal Pradesh</option>
                        <option value="jharkhand" {% if address.state == 'jharkhand' %}selected{% endif %}>Jharkhand</option>
                        <option value="karnataka" {% if address.state == 'karnataka' %}selected{% endif %}>Karnataka</option>
                        <option value="kerala" {% if address.state == 'kerala' %}selected{% endif %}>Kerala</option>
                        <option value="madhya_pradesh" {% if address.state == 'madhya_pradesh' %}selected{% endif %}>Madhya Pradesh</option>
                        <option value="maharashtra" {% if address.state == 'maharashtra' %}selected{% endif %}>Maharashtra</option>
                        <option value="manipur" {% if address.state == 'manipur' %}selected{% endif %}>Manipur</option>
                        <option value="meghalaya" {% if address.state == 'meghalaya' %}selected{% endif %}>Meghalaya</option>
                        <option value="mizoram" {% if address.state == 'mizoram' %}selected{% endif %}>Mizoram</option>
                        <option value="nagaland" {% if address.state == 'nagaland' %}selected{% endif %}>Nagaland</option>
                        <option value="odisha" {% if address.state == 'odisha' %}selected{% endif %}>Odisha</option>
                        <option value="punjab" {% if address.state == 'punjab' %}selected{% endif %}>Punjab</option>
                        <option value="rajasthan" {% if address.state == 'rajasthan' %}selected{% endif %}>Rajasthan</option>
                        <option value="sikkim" {% if address.state == 'sikkim' %}selected{% endif %}>Sikkim</option>
                        <option value="tamil_nadu" {% if address.state == 'tamil_nadu' %}selected{% endif %}>Tamil Nadu</option>
                        <option value="telangana" {% if address.state == 'telangana' %}selected{% endif %}>Telangana</option>
                        <option value="tripura" {% if address.state == 'tripura' %}selected{% endif %}>Tripura</option>
                        <option value="uttar_pradesh" {% if address.state == 'uttar_pradesh' %}selected{% endif %}>Uttar Pradesh</option>
                        <option value="uttarakhand" {% if address.state == 'uttarakhand' %}selected{% endif %}>Uttarakhand</option>
                        <option value="west_bengal" {% if address.state == 'west_bengal' %}selected{% endif %}>West Bengal</option>
                    </select>
                </div>
                





                
                <div class="col-12 mt-3 mb-3">
                    <label for="postcode" >Pincode <span>*</span></label>
                    <input type="text" name="pincode" class="form-control" id="postcode" value="{{address.pincode}}">
                </div>
                



                
                <div class="col-12 mb-3">
                    <label for="city">Town/City <span>*</span></label>
                    <input type="text" class="form-control" name="city" id="city" value="{{address.city}}">
                </div>
                
                
                <div class="col-12 mb-4">
                    <label for="email_address">Email Address <span>*</span></label>
                    <input type="email" name="email" class="form-control" id="email_address" value="{{address.email}}">
                </div>
                
                <div class="col-12 mb-3">
                    <label for="phone_number">Phone No <span>*</span></label>
                    <input type="number" class="form-control" name="phone" id="phone_number" min="0" value="{{address.phone_no}}">
                </div>
                
                <div class="col-12 mb-3">
                    <label for="street_address">Address <span>*</span></label>
                    <input type="text" class="form-control h-100 mb-3" name="address" id="street_address" value="{{address.address}}">
                    
                </div>
                
                
                <div class="col-12 mt-3 ">
                    <label for="city">Landmark<span> (optional)</span></label>
                    <input type="text" class="form-control" name="landmark" id="city" value="{{address.landmark}}">
                </div>
                
            </div>
            <input type="submit" class="btn essence-btn mt-3 mb-3"> 
        </form>
    </div>
</div>
{% endblock %}

templates/user_profile/order_items.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Orders</h2>{% endblock %}
{% block profile_base %}
<div class="col-md-9 mt-5 mx-auto ">
{% for item in items %}
                <div class="card mt-2 mb-3">
                    <div class="card-body">
                       <div class ="d-flex ">
                       <div class="image-container" style="width: 90px; height :90px;">
                            <img src="{{ item.product_id.image1.url }}" alt="Product Image">
                        </div>
                        <div class="mx-auto my-auto">
                        <h6> {{item.product_id.p_id.name}}</h6>
                        Colour: <span>{{item.product_id.color}}</span>
                        </div>
                        <div class="mx-auto my-auto">
                        
                         {{item.qty}} Item  
                        </div>
                        <div class="mx-auto my-auto">
                         
                        ₹ {{item.total_price}}
                        </div>
                        <div class="mx-auto my-auto">
                         
                        Order placed at {{item.order_id.created_at}}
                        </div>
                        {% if item.status == "Order Placed" or item.status == "Shipped" or item.status == "Delivered"%}
                        <div class="mx-auto my-auto text-success">
                         {{item.status}}
                        </div>
                        {% endif %}
                        {% if item.status == "Order Cancelled !" %}
                        <div class="mx-auto my-auto text-danger">
                         {{item.status}}
                        </div>
                        {% endif %}
                       </div>
                        <div class="mt-3">
                            <a href="{% url 'Order:user_order_details' item.id %}" class="card-link">View Details</a>
                           
                        </div>
            
                    </div>
                </div>
                {% endfor %}
            </div>
{% endblock %}

templates/user_profile/set_password.html
{% extends "profile_base/profile_base.html" %}
{% block header %} <h2>Change Password</h2>{% endblock %}
{% block profile_base %}
<form method="POST" action="{% url 'Accounts:set_password' %}">

    <div class="container">
        {% include 'alerts/alert.html' %}
        <div class="row">
            {% csrf_token %}
            <div class="row">

                <div class="col-12 mb-4">
                    <label for="email_address">New Password</label>
                    <input type="text" name="new_password" class="form-control" id="new_password" value="">
                </div>

                <div class="col-12 mb-4">
                    <label for="email_address">Confirm Password</label>
                    <input type="text" name="con_password" class="form-control" id="con_password" value="">
                </div>


            </div>
        </div>
    </div>

    <input type="submit" value="Confirm" class="btn essence-btn mt-3 mb-3">


</form>
{% endblock %}

templates/user_profile/user_order.html
{% extends "profile_base/profile_base.html" %}
{% load static %}
{% block header %} <h2>Orders</h2>{% endblock %}
{% block profile_base %}
<link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">
<div class="col-md-9 mt-5 mb-3 mx-auto ">

{% for item in items %}
                <div class="card mt-2">
                    <div class="card-body">
                       <div class ="d-flex ">
                        <div class="mx-auto">
                        <i class="fa-solid fa-location-dot fa-sm" style="color: #ff0000;"></i> {{item.address_id.city}}
                        </div>
                        <div class="mx-auto">
                        
                         {{item.created_at}}
                        </div>
                        <div class="mx-auto">
                         
                        ₹ {{item.total_price}}
                        </div>
                        <div class="mx-auto">
                         
                         {{item.status}}
                        </div>
                       </div>
                        <div class="mt-3">
                            <a href="{% url 'Order:order_items' item.id %}" class="card-link">View All Orders</a>
                           
                        </div>
                    </div>
                </div>
                {% endfor %}
                
            </div>
{% endblock %}

templates/user_profile/user_profile.html
{% extends "profile_base/profile_base.html" %}
 {% block header %} <h2>Profile</h2>{% endblock %}
{% block profile_base %}

<div class="profile-content d-flex flex-column justify-content-start  align-items-center mt-2">
        <hr>
                <form class=" user-form" action="{% url 'Users:edit_details'%}" method="POST">
                    {% csrf_token %}
                    <div class="input-group" style="width: 100%">
                        <label for="first-name">First Name</label>
                        <input type="text" id="first-name" placeholder=" Name" name="name" value="{{user_obj.first_name}}">
                    </div>
                    <div class="input-group" style="width: 100%">
                        <label for="last-name">Last Name</label>
                        <input type="text" id="last-name" placeholder="Last Name" name="lname" value="{{user_obj.last_name}}">
                    </div>
                    
                    <div class="input-group" style="width: 100%; display:none" >
                        <label for="email">Email</label>
                        <input type="email" id="email" placeholder="Email" value="{{user_obj.email}}">
                    </div>
                    <div class="input-group" style="width: 100%">
                        <label for="phone">Phone Number</label>
                        <input type="tel" id="phone" placeholder="+91" name="phone" value="{{user_obj.phone_no}}">
                    </div>
                    <button type="submit" href="{% url 'Users:edit_details' %}" class="edit-btn submit-btn vw-50">Edit</button>
                </form>
                <div class="mt-5">{% if user_obj.signup_method == 'default'%}<a href="{% url 'Accounts:change_password' %}"><h6>Change Password?</h6></a> {% endif %}
                    {% if user_obj.signup_method == 'google'%}<a href="{% url 'Accounts:set_password' %}"><h6>Set Password</h6></a> {% endif %}
                </div>
        </div>
{% endblock %}